### ISSUE TITLE
Automatically generate quotes file

### ISSUE THREAD

**Issue by leletec** [AhiruSoftwareCompany/vaq#2]
To avoid a lot of manual work, a program should be used to read the Gists-collection of quotes, anonymize the names if needed, encode it to the specified format and append the quotes file with the missing entries.
This could probably be done in any language.

**Comment by okitec** [comment]
1) The quote file comprises many different sections with different formats. Sounds like half-automated work is needed.
2) Anonymised quotes are only half the fun. I'd take the Student-Dozent quotes, but not the treasure from school. That should stay in the gist IMHO.
3) The quote file should be gitignored. Else, we could never remove quotes ever.

**Comment by leletec** [comment]
1. I agree.
2. So you would say lines 1800 - eof? That would reduce it from about 2300 lines to about 500 but I guess it's still plenty.
3. The whole `server/data/` folder should be gitignored. You just need empty files for the generated data so that the server doesn't fail.

**Comment by okitec** [comment]
2. That last part can be easily done with Awk, especially the single-line ones. You could give it a try, it's an one-liner. :P

**Comment by leletec** [comment]
3. Done, see b994ffd8f30e26a2e949b216f57b47a499e225bc.

**Comment by leletec** [comment]
2. I've got a lot to do the following weeks, so why don't you implement it real quick? :smile:

**Comment by okitec** [comment]
2. Where's the fun in that? Trying a new language is so much fun and the code is extremely straightforward for the single-line quotes, so much so that I wouldn't speak of 'implementing'. Furthermore, this is not urgent.

**Comment by leletec** [comment]
So I didn't do that much with awk, but it looks like it works. :smiley:
