### ISSUE TITLE
Implement a login functionality

### ISSUE THREAD

**Issue by leletec** [AhiruSoftwareCompany/vaq#9]
The quotelist should be obfuscated, i.e. the names should be redacted and replaced with generics like "Schüler", "Student" or "Dozent".

**Comment by leletec** [comment]
Alternatively, a login could  be used to make sure noone sees what he shouldn't.
What do you think @dieechtenilente @okitec ?

**Comment by okitec** [comment]
Some variant of the latter, since a redaction would take a lot of context out of the quote.
